"""Training script for MathMirror. Bootstrap-to-byte, no human labels.

Usage:
    python -m math_mirror.train --epochs 100 --batch_size 256
    python -m math_mirror.train --resume checkpoint.pt --epochs 50

Every training example is generated by bootstrap and verified by SymPy.
No external dataset. No human annotation. Pure self-supervised math.
"""

import argparse
import os
import time
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

from .model import MathMirror, encode_ascii, decode_ascii
from .bootstrap import MathBootstrap
from .verifier import MathVerifier


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train MathMirror")
    # architecture
    p.add_argument("--d_model", type=int, default=256)
    p.add_argument("--n_layers", type=int, default=12)
    p.add_argument("--n_heads", type=int, default=8)
    p.add_argument("--ctx_len", type=int, default=2048)
    # training
    p.add_argument("--batch_size", type=int, default=256)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--epochs", type=int, default=100)
    p.add_argument("--grad_clip", type=float, default=1.0)
    p.add_argument("--weight_decay", type=float, default=0.01)
    p.add_argument("--warmup_steps", type=int, default=100)
    # data
    p.add_argument("--examples_per_epoch", type=int, default=4096,
                   help="Number of bootstrap examples generated per epoch")
    p.add_argument("--max_seq_len", type=int, default=256,
                   help="Max sequence length for training examples (pad/truncate)")
    # checkpoint
    p.add_argument("--resume", type=str, default=None,
                   help="Path to checkpoint to resume from")
    p.add_argument("--checkpoint_dir", type=str, default="checkpoints",
                   help="Directory to save checkpoints")
    p.add_argument("--save_every", type=int, default=10,
                   help="Save checkpoint every N epochs")
    # verification
    p.add_argument("--verify_every", type=int, default=5,
                   help="Run verification sampling every N epochs")
    p.add_argument("--verify_samples", type=int, default=50,
                   help="Number of samples to verify")
    # device
    p.add_argument("--device", type=str, default=None,
                   help="Device (auto-detected if not set)")
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()


def get_device(requested: str | None) -> torch.device:
    """Auto-detect best available device."""
    if requested:
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def encode_batch(examples: list[str], max_len: int) -> torch.Tensor:
    """Encode a list of math strings to a padded byte tensor.

    Each string is converted to ASCII bytes, truncated or zero-padded
    to max_len. Returns (N, max_len) long tensor.
    """
    batch = torch.zeros(len(examples), max_len, dtype=torch.long)
    for i, ex in enumerate(examples):
        try:
            raw = ex.encode("ascii", errors="ignore")
            length = min(len(raw), max_len)
            batch[i, :length] = torch.tensor(list(raw[:length]), dtype=torch.long)
        except Exception:
            pass  # leave as zeros (will contribute minimal loss)
    return batch


def lr_with_warmup(step: int, warmup_steps: int, base_lr: float) -> float:
    """Linear warmup then constant (scheduler handles decay)."""
    if step < warmup_steps:
        return base_lr * (step + 1) / warmup_steps
    return base_lr


def save_checkpoint(model: MathMirror, optimizer: AdamW,
                    epoch: int, step: int, loss: float,
                    args: argparse.Namespace, path: str):
    """Save training checkpoint."""
    torch.save({
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "epoch": epoch,
        "step": step,
        "loss": loss,
        "config": {
            "d_model": args.d_model,
            "n_layers": args.n_layers,
            "n_heads": args.n_heads,
            "ctx_len": args.ctx_len,
        },
    }, path)


def load_checkpoint(path: str, device: torch.device):
    """Load checkpoint, return (model, optimizer_state, epoch, step)."""
    ckpt = torch.load(path, map_location=device, weights_only=False)
    cfg = ckpt["config"]
    model = MathMirror(
        d_model=cfg["d_model"],
        n_layers=cfg["n_layers"],
        n_heads=cfg["n_heads"],
        ctx_len=cfg["ctx_len"],
    )
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    return model, ckpt["optimizer_state_dict"], ckpt["epoch"], ckpt["step"]


def verify_model_outputs(model: MathMirror, verifier: MathVerifier,
                         n_samples: int, device: torch.device) -> dict:
    """Sample model outputs and verify them symbolically.

    Returns dict with counts of valid/invalid/error and sample outputs.
    """
    model.eval()
    prompts = [
        "2+3=", "7*8=", "d/dx(x**2)=", "d/dx(x**3)=",
        "15+27=", "100-37=", "12*11=", "d/dx(5*x)=",
        "(x+1)*(x+2)=", "det([[1,0],[0,1]])=",
    ]
    results = {"valid": 0, "invalid": 0, "error": 0, "samples": []}

    for i in range(n_samples):
        prompt = prompts[i % len(prompts)]
        try:
            output_bytes = model.generate(
                prompt.encode("ascii"), max_len=64, temperature=0.3
            )
            output_str = output_bytes.decode("ascii", errors="replace").strip()
            # check if output contains a valid identity
            is_valid = verifier.check_identity(output_str)
            if is_valid:
                results["valid"] += 1
            else:
                results["invalid"] += 1
            if i < 5:  # log first 5 samples
                results["samples"].append({
                    "prompt": prompt,
                    "output": output_str,
                    "valid": is_valid,
                })
        except Exception as e:
            results["error"] += 1
            if i < 5:
                results["samples"].append({
                    "prompt": prompt,
                    "output": f"ERROR: {e}",
                    "valid": False,
                })

    model.train()
    return results


def log(msg: str):
    """Simple timestamped logging to stdout."""
    t = time.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{t}] {msg}", flush=True)


def train(args: argparse.Namespace):
    """Main training loop."""
    torch.manual_seed(args.seed)

    device = get_device(args.device)
    log(f"Device: {device}")

    # Create checkpoint directory
    ckpt_dir = Path(args.checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    # Initialize or resume
    start_epoch = 0
    global_step = 0
    optimizer_state = None

    if args.resume:
        log(f"Resuming from {args.resume}")
        model, optimizer_state, start_epoch, global_step = load_checkpoint(
            args.resume, device
        )
        log(f"Resumed at epoch {start_epoch}, step {global_step}")
    else:
        model = MathMirror(
            d_model=args.d_model,
            n_layers=args.n_layers,
            n_heads=args.n_heads,
            ctx_len=args.ctx_len,
        )
        model.to(device)

    param_count = model.param_count()
    log(f"Model parameters: {param_count:,}")

    # Optimizer
    optimizer = AdamW(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )
    if optimizer_state is not None:
        optimizer.load_state_dict(optimizer_state)

    scheduler = CosineAnnealingLR(
        optimizer, T_max=args.epochs * (args.examples_per_epoch // args.batch_size)
    )

    # Bootstrap and verifier
    bootstrap = MathBootstrap()
    verifier = MathVerifier()

    log(f"Training config: epochs={args.epochs}, batch_size={args.batch_size}, "
        f"lr={args.lr}, examples_per_epoch={args.examples_per_epoch}")
    log("=" * 60)

    model.train()
    avg_loss = 0.0

    for epoch in range(start_epoch, start_epoch + args.epochs):
        epoch_loss = 0.0
        epoch_steps = 0
        epoch_start = time.time()

        # Generate fresh data each epoch (bootstrap is infinite)
        examples = bootstrap.generate_batch(args.examples_per_epoch)
        if not examples:
            log(f"Epoch {epoch}: bootstrap produced 0 examples, skipping")
            continue

        log(f"Epoch {epoch}: generated {len(examples)} verified examples")

        # Process in mini-batches
        for batch_start in range(0, len(examples), args.batch_size):
            batch_examples = examples[batch_start:batch_start + args.batch_size]
            if len(batch_examples) < 2:
                continue

            batch_tensor = encode_batch(batch_examples, args.max_seq_len)
            batch_tensor = batch_tensor.to(device)

            # Skip batches that are all padding
            if batch_tensor.sum() == 0:
                continue

            # Warmup LR
            if global_step < args.warmup_steps:
                warmup_lr = args.lr * (global_step + 1) / args.warmup_steps
                for pg in optimizer.param_groups:
                    pg["lr"] = warmup_lr

            # Forward + backward
            loss = model.compute_loss(batch_tensor)
            optimizer.zero_grad()
            loss.backward()

            # Gradient clipping
            if args.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)

            optimizer.step()
            if global_step >= args.warmup_steps:
                scheduler.step()

            epoch_loss += loss.item()
            epoch_steps += 1
            global_step += 1

        # Epoch stats
        elapsed = time.time() - epoch_start
        avg_loss = epoch_loss / epoch_steps if epoch_steps > 0 else float("nan")
        current_lr = optimizer.param_groups[0]["lr"]
        log(f"Epoch {epoch}: loss={avg_loss:.4f}, lr={current_lr:.2e}, "
            f"steps={epoch_steps}, time={elapsed:.1f}s")

        # Periodic verification
        if (epoch + 1) % args.verify_every == 0:
            vr = verify_model_outputs(model, verifier, args.verify_samples, device)
            log(f"  Verification: {vr['valid']}/{args.verify_samples} valid, "
                f"{vr['invalid']} invalid, {vr['error']} errors")
            for s in vr["samples"]:
                mark = "OK" if s["valid"] else "FAIL"
                log(f"    [{mark}] {s['prompt']} -> {s['output'][:80]}")

        # Periodic checkpoint
        if (epoch + 1) % args.save_every == 0:
            ckpt_path = str(ckpt_dir / f"mathm_epoch{epoch}.pt")
            save_checkpoint(model, optimizer, epoch, global_step, avg_loss, args, ckpt_path)
            log(f"  Checkpoint saved: {ckpt_path}")

    # Final checkpoint
    final_path = str(ckpt_dir / "mathm_final.pt")
    save_checkpoint(model, optimizer, start_epoch + args.epochs - 1,
                    global_step, avg_loss, args, final_path)
    log(f"Final checkpoint saved: {final_path}")
    log("Training complete.")


def main():
    args = parse_args()
    train(args)


if __name__ == "__main__":
    main()
